"""Native Kafka client and JSON codec (Rust, see packages/tkati-core/src/)."""

from collections.abc import Mapping, Sequence

import pyarrow as pa

class KafkaError(Exception):
    """An error reported by librdkafka."""

class BatchOffsets:
    """Where a consumed batch lies in each partition. Opaque: only handed back
    to `NativeConsumer.commit` / `rewind`."""

    def __init__(self) -> None:
        """An empty set, for tests that mock a consumer."""

class RawBatch:
    """One consumed batch. Supports the buffer protocol: the payloads as
    newline-delimited JSON, tombstones omitted."""

    errors: list[str]
    offsets: BatchOffsets
    tombstones: int

    @staticmethod
    def from_payloads(payloads: Sequence[bytes | None]) -> RawBatch: ...
    def __len__(self) -> int: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
    def payloads(self) -> list[bytes | None]: ...

class EncodedBatch:
    """Messages ready to enqueue: a payload and optional key each."""

    @staticmethod
    def from_payloads(messages: Sequence[tuple[bytes, str | None]]) -> EncodedBatch: ...
    def __len__(self) -> int: ...
    def payloads(self) -> list[bytes]: ...
    def keys(self) -> list[str | None]: ...

def encode_arrow(
    data: pa.Table | pa.RecordBatch,
    key_column: str | None = None,
    keys: Sequence[str | None] | None = None,
) -> EncodedBatch: ...

class NativeConsumer:
    def __init__(self, config: Mapping[str, object], topic: str) -> None: ...
    def poll_batch(self, timeout: float, max_messages: int) -> RawBatch: ...
    def commit(self, offsets: BatchOffsets) -> None: ...
    def rewind(self, offsets: BatchOffsets) -> None: ...
    def close(self) -> None: ...

class NativeProducer:
    def __init__(self, config: Mapping[str, object], topic: str) -> None: ...
    def enqueue(self, batch: EncodedBatch) -> None: ...
    def flush(self) -> None: ...
